### ISSUE TITLE
removal of port from default endpoint url in selection

### ISSUE THREAD

**Issue by Stephenitis** [segmentio/integration-iron-io#5]
@amillet89 Hey guys, quick fix is needed

Removal of the port from the default endpoint from the prior pull request #3 

remove :443

ccing, @ysadka

**Comment by amillet89** [comment]
@Stephenitis, looks like there was a bug in our settings migration. I've added the two new settings to all enabled projects at Segment, which was causing requests to fail. Also removed the port number by default, but looks like that wasn't causing an issue either way. sorry!
