### ISSUE TITLE
Rename Label

### ISSUE THREAD

**Issue by ysadka** [segmentio/integration-iron-io#6]
Would you change this to say API Version instead of Endpoint? Users are getting confused with the duplicate labels

![screen shot 2015-02-13 at 11 38 57 am](https://cloud.githubusercontent.com/assets/3474501/6194007/266b6a04-b375-11e4-8866-138203f60a14.png)

Thanks guys, we appreciate it :)

**Comment by ndhoule** [comment]
Whoops, sorry for not getting to this earlier. Fixed, thanks for the heads up!
