### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by jhabdas** [segmentio/integration-iron-io#8]
I'm created [an issue against IronMQ](https://github.com/iron-io/splunk-ironmq-mi/issues/2) to help support the way Segment data is sent to Splunk using their Splunk Modular Input. I came up with the idea after reading the article titled [How to Build an ETL Pipeline for ElasticSearch Using Segment and Iron.io](http://www.iron.io/how-to-build-etl-pipeline-for/).

It would be great if someone from Segment could weigh in on the approach and possibly help us lock down the best possible approach for sending data with Segment used as the extraction step of the ETL process. Either way, thanks for considering.

**Comment by bbeaird** [comment]
Closed per request of customer.
